export const FETCH_STORES_PENDING = 'FETCH_STORES_PENDING';
export const FETCH_STORES_SUCCESS = 'FETCH_STORES_SUCCESS';
export const FETCH_STORES_ERROR = 'FETCH_STORES_ERROR';

export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';

export const FETCH_CATALOG_PENDING = 'FETCH_CATALOG_PENDING';
export const FETCH_CATALOG_SUCCESS = 'FETCH_CATALOG_SUCCESS';
export const FETCH_CATALOG_ERROR = 'FETCH_CATALOG_ERROR';

export const FETCH_INGREDIENTS_PENDING = 'FETCH_INGREDIENTS_PENDING';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_ERROR = 'FETCH_INGREDIENTS_ERROR';

export const ADD_ITEM_TO_INGREDIENTS_LIST = 'ADD_ITEM_TO_INGREDIENTS_LIST';
export const REMOVE_ITEM_FROM_INGREDIENTS_LIST =
  'REMOVE_ITEM_FROM_INGREDIENTS_LIST';
export const DELETE_ITEM_FROM_INGREDIENTS_LIST =
  'DELETE_ITEM_FROM_INGREDIENTS_LIST';

export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
